### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by vuillaut** [atlas-outreach-data-tools/atlas-outreach-cpp-framework-13tev#4]
consider adding a LICENSE file please

**Comment by artfisica** [comment]
Hi @vuillaut,

This is such an obvious thing have. Thank you for the recommendation!
I added a License to the code: https://github.com/atlas-outreach-data-tools/atlas-outreach-cpp-framework-13tev/blob/master/LICENSE

And I will create a new tag to propagate the change to our current record.
